token_expire: 3600
http_port: 8084

services:
  db_service: "http://localhost:8083"
  login_service: "http://localhost:8084"
  game_service: "http://localhost:8082"
  registry_service: "http://localhost:8081"  # 服务注册中心地址（独立服务）
